aan.amazon-adsystem.com 
aan.amazon.com 
aax-us-east.amazon-adsystem.com 
aax-us-pdx.amazon-adsystem.com 
aax.amazon-adsystem.com 
c.amazon-adsystem.com 
fls-na.amazon.ca 
fls-na.amazon.com 
mads.amazon-adsystem.com 
s.amazon-adsystem.com 
mag-na.amazon.com
amazon.ca
amzn.ca
api.amazon.ca
analytics.xcal.tv
z.moatads.com


aax.amazon-adsystem.com
aax-eu.amazon-adsystem.com
aax-us-east.amazon-adsystem.com
aax-us-pdx.amazon-adsystem.com
amazonaws.com
amazon.com
amazon.co.uk
amazon.in
amzn.com
amzn.to
cognito-identity.us-east-1.amazonaws.com
completion.amazon.co.uk
det-ta-g7g.amazon.com
device-messaging-na.amazon.com
device-metrics-us-2.amazon.com
device-metrics-us.amazon.com
fls-eu.amazon.com
fls-eu.amazon.de
fls-na.amazon-adsystem.com
fls-na.amazon.com
images-na.ssl-images-amazon.com
ir-na.amazon-adsystem.com
ir-uk.amazon-adsystem.com
kinesis.us-east-1.amazonaws.com
mads.amazon-adsystem.com
mads.amazon.com
mas-sdk.amazon.com
ocsp.rootg2.amazontrust.com
s3.amazonaws.com
s3.ap-northeast-2.amazonaws.com
s3.ap-south-1.amazonaws.com
s3-ap-southeast-1.amazonaws.com
s3-eu-west-1.amazonaws.com
s3-us-west-2.amazonaws.com
s.amazon-adsystem.com
smile.amazon.com
spectrum.s3.amazonaws.com
sqs.us-east-1.amazonaws.com
unagi-na.amazon.com
us-east-1.amazonaws.com
